### ISSUE TITLE
Gadfly...

### ISSUE THREAD

**Issue by PaulSoderlind** [AsafManela/LassoPlot.jl#1]
Hi,
LassoPlot.jl looks nice. On a first glance, it looks like it wouldn't be too difficult to generalise it (so as not to depend on Gadfly only). Am I right? If so, it would be great to have an output from the package that could be used with Plots or PyPlot. If not, sorry for the noise.

**Comment by AsafManela** [comment]
Thanks, and yes, supporting Plots.jl makes a lot of sense
